/** @format */

export const workExps = [
  {
    id: 8,
    company: "Amazon",
    title: "Software Dev Engineer I",
    location: "Toronto, ON",
    description: [
      "Delivered major projects in the Amazon Advertising Console including the Multi-countries Dashboard (landing page), Global Campaigns (SVP goal), and Unified Sponsored Ads/DSP Ad Console Landing Page (S-team goal) serving 1.5M+ advertisers WW, and driving $X00M+ in WW revenue opportunities",
      "Key contributor to development of internal dashboard framework (Typescript (React), GraphQL, Java (Spring), RESTful APIs, Jest) saving ~15 years annual dev time, delivering core components and service resolvers w/ integration tests",
      "Led the design & development of the Global Campaigns Settings Detail page in the Amazon Advertising Console using Redux, React, and RESTful APIs to streamline campaign configuration for advertisers",
      "Implemented global budget rules & budget recommendations across multi-country campaigns through React components development on the frontend with Java backend data aggregation services",
      "Designed, developed and integrated key, re-usable components for several landing pages across Sponsored Ads and DSP surfaces via Server-side frameworks (Modern.js, Zustand, Tanstack Query)",
      "Accelerated developer velocity by strengthening CI/CD pipelines with Cypress E2E and GraphQL/REST integration tests",
      "Leveraged AWS (ECS, CloudWatch, IAM, CloudFormation, S3) for containerized deployments, monitoring/debugging, access control, infrastructure automation, and compliance",
      "Partnered with PMs, TPMs, SDMs, UX engineers and cross-functional teams to streamline technical implementation and alignment with customers/stakeholders",
    ],
    startDate: "Jan 2024",
    endDate: "Present",
  },
  {
    id: 0,
    company: "Amazon",
    title: "Software Developer Engineer Intern",
    location: "Toronto, ON",
    description: [
      "Developed, tested, and deployed full-stack, internationalized features (22 countries) whilst leveraging Java, React (Typescript, Javascript, Redux, Jest) for the Advertising Console product within the Amazon Ads org",
      "Spearheaded and delivered key features pertaining to a VP goal for about 90, 000 unique advertisers (per month) and 250, 000 total advertisers (per month)",
      "Devised technical strategies by diagnosing architectural software approaches while collaborating closely with key stakeholders, estimating effort & work for features, and executing task planning to exactitude",
      "Constructed a QuickSight dashboard for business intelligence analysis & improved operational excellence for internal UI library by approximately 75%",
    ],
    startDate: "June 2022",
    endDate: "Aug 2022",
  },
  {
    id: 1,
    company: "IBM",
    title: "Software Developer Intern",
    location: "Toronto, ON",
    description: [
      "Drove implementation of Process Admin Console of IBM Business Process Manager software from a legacy web application in a scrum environment",
      "Refactored, designed and developed 10+ Full-Stack pages in React with Typescript (ES6+), CSS, Redux, IBM’s Carbon Design System from JSP, GWT pages written in Java",
      "Developed RESTful APIs through the OpenAPI Specification and refactored Java EE backend logic, as well as composed DB2 SQL queries",
      "Implemented i18n (internationalization) as well as IBM standardized accessibility requirements within the SPA",
      "Utilized Jira, Git, Jenkins, JFrog Artifactory and IBM RTC to organize tasks through functional needs and manage CI/CD pipelines",
      "Investigated and produced fixes for defects and bugs within the IBM Business Process Manager software",
    ],
    startDate: "May 2021",
    endDate: "June 2022",
  },
  {
    id: 2,
    company: "Toronto Metropolitan University",
    title: "Research Assistant",
    location: "Toronto, ON",
    description: [
      "Spearheaded the development of VR software within Unity3D (C#) using the HP Reverb G2 headset with the Tobii SDK, XR Interaction Toolkit, Windows Mixed Reality Portal for a myriad of medical research/hospital/paediatric use cases including eye tracking, heatmap generation, pupil diameter, cognitive load, heart rate, and much more",
      "Explored and implemented ML (1D-CNN) model deployment (Edge AI) onto Unity3D with C# on several OS (Android, etc.) via PyTorch/ONNX model conversion, saving 70% of budget on cloud computation",
      "Trained Photoplethysmography (PPG) signal 1D-CNN model for stress classification from DEAP dataset using data augmentation, hyper-parameter optimization, batch normalization & dropout methods to achieving 82% training accuracy",
      "Collaborated with Director/Supervisor Naimul Khan at TMU Multimedia lab, post-doctorate, and several RA constituents for in-game emotion recognition for therapeutic VR games",
    ],
    startDate: "May 2023",
    endDate: "Aug 2023",
  },
  {
    id: 3,
    company: "Innovation Boost Zone - Aetava",
    title: "Frontend Developer",
    location: "Toronto, ON",
    description: [
      "Developed and integrated a custom-made mood board plugin for a WordPress application",
      "Implemented a React + Canvas app using Javascript & HTML/CSS, utilizing the WooCommerce API",
    ],
    startDate: "Sep 2022",
    endDate: "Dec 2022",
  },
  {
    id: 4,
    company: "Helium Aero",
    title: "Android Application Developer",
    location: "Toronto, ON",
    description: [
      "Developed an Android application (Java) that interfaces with drones from scratch based off of Figma prototype",
      "Utilized Java & XML to build Android application along with a Mavlink Java library to communicate between drone",
      "Employed UDP communication between simulated drone and Android devices to send and receive Mavlink packets",
    ],
    startDate: "Mar 2021",
    endDate: "Jul 2021",
  },
  {
    id: 5,
    company: "Lightening Group LLC.",
    title: "Frontend Developer",
    location: "Remote",
    description: [
      "Developed a frontend using React paired with the Next.js framework, Typescript, Tailwind CSS to format components, as well as GraphQL to communicate with the backend",
      "Worked with a client geared toward launching a pharmaceutical web application, and collaborated with a team of developers through Git",
      "Utilized Cypress to conduct E2E testing to ensure bugs weren’t present in codebase as well as ensure seamless delivery",
    ],
    startDate: "Sep 2020",
    endDate: "Dec 2020",
  },
  {
    id: 6,
    company: "Toronto Metropolitan University",
    title: "Undergraduate Research Assistant",
    location: "Toronto, ON",
    description: [
      "Researched and compared different MQTT Mosquitto Clustering implementations based on latency and design aspects",
      "Analysed 1000+ lines of code written in C to document structure and components of clusters",
      "Conducted localized broker testing & assisted with configuration & deployment of MQTT Clusters into the cloud",
    ],
    startDate: "Jun 2020",
    endDate: "Aug 2020",
  },
  {
    id: 7,
    company: "Balancever",
    title: "Android Developer",
    location: "Toronto, ON",
    description: [
      "Spearheaded a Full-stack Android (Java, XML, Gradle) application from scratch in an Agile environment; utilizing Git to coordinate with other developers",
      "Instituted backend with Firebase Auth (3rd Party OAuth2) & Realtime Database; integrating several APIs (ie. GCP)",
      "Constructed several algorithms to create a custom android calendar and sort events",
    ],
    startDate: "May 2020",
    endDate: "Aug 2020",
  },
];

export const projects = [
  {
    id: 0,
    title: "SmartFridgeAddOn",
    short_description: "IoT Embedded device + Machine Learning + Web App",
    description:
      "My Computer Engineering undergraduate capstone project (spanning over two semesters). Our objective was to design an add-on package for existing fridges through an easy to install hardware rig coupled with an intelligent cloud-based analysis software that could turn any fridge into a 'smart' one.",
    image: `images/SFAO.png`,
    tags: [
      "Python",
      "PyTorch",
      "YOLOv7",
      "Roboflow",
      "Flask",
      "Luxonis SDK",
      "Bash scripts",
      "Raspbian",
      "Raspberry Pi Zero 2 W",
      "Oak-D-Lite",
      "Google Colab",
      "React",
      "CSS",
      "Firebase Auth",
      "Firebase Cloudstore DB",
      "Jira",
    ],
    code: "https://github.com/DeluxeViper/SmartFridgeAddOn",
    demo: "",
  },
  {
    id: 1,
    title: "DAO Blockchain DApp",
    short_description: "Full Stack Blockchain Decentralized Application",
    description: "A decentralized application for a DAO (decentralized autonomous organization) that allows ETH blockchain users to create and vote for customized elections/proposals. These proposals can be customized with augmented voting mechanisms such as Quadratic Voting and a linear time decay.",
    image: "images/DAO_DApp.png",
    tags: [
      "React",
      "Solidity",
      "Javascript",
      "Truffle",
      "Web3.js",
      "Tailwindcss",
      "Ganache",
      "Metamask",
      "IPFS",
    ],
    code: "https://github.com/DeluxeViper/ECE1770-QV-DAO-DApp-Project/tree/main",
    demo: "https://quadradao-app.azurewebsites.net"
  },
  {
    id: 2,
    title: "SmoothieMakersClub",
    short_description: "Full Stack Web Application",
    description:
      "A Progressive Web Application that brings all Smoothie Makers alike to come together, create healthy & nutritious recipes, and share them with each other.",
    image: `images/SmoothieWebsite.png`,
    tags: [
      "Java",
      "Python",
      "Spring Boot",
      "MySQL",
      "Javascript",
      "CSS",
      "HTML",
      "Spring Data JPA",
      "AWS Elastic Beanstalk",
      "AWS RDS",
      "BeautifulSoup4",
      "Selenium",
      "Vaadin",
      "OAuth2.0",
    ],
    code: "https://github.com/DeluxeViper/SmoothieWebsite",
    demo: "",
  },
  {
    id: 3,
    title: "MemoryGo",
    short_description: "Cross-Platform Mobile Application",
    description:
      "MemoryGo is a flashcard tool that lets you study without realization while you play games, surf the internet, watch a video, chat with friends or any other task.",
    image: `images/MemoryGo.png`,
    tags: ["Dart", "Java (Android)", "XML", "SQL (SQLite)", "Gradle"],
    code: "https://github.com/DeluxeViper/Memorygo",
    demo: "https://play.google.com/store/apps/details?id=com.ceruleansource.MemoryGo",
  },
  {
    id: 4,
    title: "Cooking Recipe Suggestion Web App",
    short_description: "Full Stack Web Application",
    description:
      "With 1930 ingredients and 1489 recipes, Cook.io is a web application that provides cooking recipes to users based on the ingredients they input.",
    image: `images/CRS-Web-App.png`,
    tags: [
      "Javascript",
      "Express.",
      "React",
      "MaterialUI",
      "Python",
      "Redis (caching)",
      "Firebase Auth",
      "Firebase Cloud Firestore",
      "Jira",
      "Figma",
    ],
    code: "https://github.com/DeluxeViper/Cooking-Recipe-Suggestion-Web-App",
    demo: "",
  },
  {
    id: 5,
    title: "Livestream App",
    short_description: "Android Mobile Application",
    description:
      "A mobile app that allows the user to either broadcast their own stream and/or find and join streams happening around them through a google maps populated with a series of markers that indicate the myriad of logged in users that might or might not be streaming.",
    image: `images/livestream.jpeg`,
    tags: ["Kotlin", "XML", "Room", "Retrofit", "OkHttp3", "Dagger", "GCP"],
    code: "https://github.com/DeluxeViper/LivestreamApp",
    demo: "",
  },
  {
    id: 6,
    title: "Livestream Backend",
    short_description: "RESTful API Backend",
    description:
      "A backend for a livestreaming client application that consumes it. This backend's capabilities ranges from JWT user authentication, to being able to manage the MongoDB database that it's connected to.",
    image: `images/server.jpeg`,
    tags: [
      "Java",
      "Spring (Boot, Security, Web, Reactive MongoDB)",
      "MongoDB",
      "JWT",
      "NGINX",
      "RTMP",
      "Docker (Compose)",
    ],
    code: "https://github.com/DeluxeViper/livestreambackend-mongodb",
    demo: "",
  },
  {
    id: 7,
    title: "Torrent Clone",
    short_description: "P2P CLI application",
    description:
      "A P2P application (created in C) that allows peers to share and download content through an index server via UDP and TCP communication. (Complete technical description on github)",
    image: `images/p2p_image.jpeg`,
    tags: ["C", "UDP", "TCP", "GCC", "Makefile"],
    code: "https://github.com/DeluxeViper/TorrentClone",
    demo: "",
  },
  // {
  //   id: 7,
  //   title: "Air Traffic Control System",
  //   short_description: "Distributed System - CLI Application",
  //   description:
  //     "Collaborated with a team of 4 individuals to create an Air Traffic Control System that uses technologies such as RabbitMQ and gRPC to ensure a distributed, scalable, secure and robust system inspired by the AeroMACS communication system (with some modifications).",
  //   image: `images/ATS.jpg`,
  //   tags: ["Python", "RabbitMQ", "gRPC", "Docker compose"],
  //   code: "https://github.com/nigel5/air-traffic-control-system",
  //   demo: "",
  // },
];

export const TimeLineData = [
  {
    year: 2018,
    month: "Sept",
    text: "Started Computer Engineering B. Eng at Toronto Metropolitan University",
  },
  {
    year: 2021,
    month: "May",
    text: "Started IBM SWE internship",
  },
  {
    year: 2022,
    month: "May",
    text: "Ended IBM SWE internship",
  },
  {
    year: 2023,
    month: "Aug",
    text: "Completed Amazon internship",
  },
  {
    year: 2023,
    month: "May",
    text: "Graduated with a Computer Engineering (B. Eng) degree from Toronto Metropolitan University",
  },
  {
    year: 2023,
    month: "Sep",
    text: "Started MEng at UofT",
  },
  {
    year: 2024,
    month: "January",
    text: "SDE 1 at Amazon",
  }
];
